// (stateEnum, on_init, on_update, on_exit)
DEF_STATE_INFO(GAME_STATE_SPLASH_SCREEN, splash_screen_on_init, splash_screen_on_update, splash_screen_on_exit) 
DEF_STATE_INFO(GAME_STATE_MAIN_MENU, _game_main_menu_on_init, _game_main_menu_on_update, _noop)
DEF_STATE_INFO(GAME_STATE_PLAYING, _game_round_on_init, _game_playing_on_update, _noop)
DEF_STATE_INFO(GAME_STATE_ROUND_END, _noop, _game_round_end_on_update, _game_round_end_on_exit)
DEF_STATE_INFO(GAME_STATE_SHOP, _noop, _game_shop_on_update, _game_shop_on_exit)
DEF_STATE_INFO(GAME_STATE_BLIND_SELECT, _noop, _game_blind_select_on_update, _game_blind_select_on_exit)
DEF_STATE_INFO(GAME_STATE_LOSE, _game_lose_on_init, _game_lose_on_update, _game_over_on_exit)
DEF_STATE_INFO(GAME_STATE_WIN, _game_win_on_init, _game_win_on_update, _game_over_on_exit)
